language: node_js

node_js:
  - 12

  env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greeting_test

before_script:
  - psql -c 'create database greeting_test;' -U postgres
  - psql -U postgres -d greeting_test -a -f database.sql

services:
  - postgresql